name: Deploy on FTP
on: 
  push:
    branches:
      - main
      - ourworkprocess
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get lastest code
      uses: actions/checkout@v3
    - name: Upload files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: s31.mydevil.net
        username: ${{secrets.username_ftp}}
        password: ${{secrets.password_ftp}}
        server-dir: public_html/adrian_flak
